from telethon.sync import TelegramClient
from telethon.tl.functions.messages import GetDialogsRequest
from telethon.tl.types import InputPeerEmpty
import logging
import networkx as nx
import os
import networkx as nx
from networkx.algorithms import bipartite
import matplotlib.pyplot as plt

from typing import List

import Constants as const
from process_group import get_groups_data
logging.basicConfig(format='[%(levelname) 5s/%(asctime)s] %(name)s: %(message)s',
                    level=logging.INFO)

client = TelegramClient(
            'anon', 
            const.credentials['api_id'], 
            const.credentials['api_hash']
        )


async def main():
    hints = [
        "@donald_j_trump_q_family_germany",
        "@defender_shaef_2q2q",
        "@qanons_deutschland",
        "@qanon_world",
        "@kaisertreu_ewig",
        "@deutschlandtreff",
        "@digitalerchronist_allgemeinchat",
        "@betfury_de",
        "@cryptomondayde",
        "@gaynudesger",
        "@pokemongoger",
        "@germanfurrygroup",
        "@binancegerman",
        "@technicall_crypto",
        "@oliverjanich",
        "@Kulturstudio",
        "@kenjebsen",
        "@ATTILAHILDMANN",
        "@SchrangTV",
        "@EvaHermanOffiziell",
        "@Xavier_Naidoo",
        "@FaktenFriedenFreiheit",
        "@unblogd",
        "@silberjungeoffiziell",
        "@AllesAusserMainstream",
        "@HaunsiAppmann",
        "@unzensiert",
        "@Ayse_Meren",
        "@FreieMedienTV",
        "@nachrichtenportal",
        "@wirsindvielmehr",
        "@dawidsnowden",
        "@antiilluminaten",
        "@fufmedia",
        "@DigitalSoldiersGermanyNews",
        "@LIONMediaTelegram",
        "@AntiZensur",
        "@Haintz",
        "@vereinigteWahrheitsbewegung",
        "@TrueSecrets",
        "@DigitalChronist",
        "@gerechtigkeitfuersvaterland",
        "@bitteltv",
        "@CheckMateNews",
        "@GeheimeswissenderEliten",
        "@GFTV_HH",
        "@Daniel_Prinz_Offiziell",
        "@samueleckert",
        "@TrueLife18",
        "@blaupausetv",
        "@DieWahrheitundnurdieWahrheit",
        "@FreiheitDerGedanken",
        "@AnonymousSchweizOrginal",
        "@Medienzensur",
        "@gesperrtBRD",
        "@coachcecil",
        "@unblogd",
        "@ConnectivEvents",
        "@neverforgetnikiblog",
        "@stefanmagnet",
        "@ketzerderneuzeit",
        "@tolzin",
        "@nachrichtvonmueller",
        "@hagengrell",
        "@gunnarkaisertv",
        "@ignazbearth",
        "@martinsellnerIB",
        "@buergerinformative",
        "@LIONMediaTelegram",
        "@der_impulsgeber",
        "@politische_bildersprueche",
        "@frieden_rockt_offiziell",
        "@wdchurschweiz",
        "@verbindediepunkte",
        "@FREIHEITmachtWAHR",
        "@dsindf",
        "@Conspiracyfactsdeutsch",
        "@wahrheitstraeumer",
        "@derdeutschamerikaner",
        "@gehlkenronald",
        "@whattheyhide",
        "@endzeitreportmcm",
        "@ursprunc",
        "@GWisnewski",
        "@charleskrueger",
        "@nityatelegram",
        "@BitchBotBoiiLive",
        "@wissenistmacht1",
        "@ATTILAHILDMANN_2",
        "@TAO_TheorieAllerOrdnung",
        "@Q_D_R_A",
        "@Q_Faktor_Germany",
        "@QanonAustria",
        "@q_anonymous_kanal_deutschland",
        "@rabbitresearch",
        "@QlobalChange",
        "@Adrenocrime",
        "@WE_R_Q",
        "@SandySteen1",
        "@INTO_THE_LIGHT_NEWS",
        "@Aufklaerung_Grundlagen",
        "@Q_Channel_de",
        "@QAnonInternationalInfo",
        "@QAnons_Channel_Germany",
        "@Qparadise",
        "@DEFENDER_SHAEF_2Q2Q",
        "@QWWG1WGA16PLUS1",
        "@der17stammtisch",
        "@yellowroses2Q2Q",
        "@q_proofs",
        "@KlagemauerTV",
        "@eingeSCHENKt",
        "@ExpressZeitung",
        "@CompactMagazin",
        "@uncut_news",
        "@oliverflesch",
        "@Servus_TV",
        "@wochenblick",
        "@LegitimNews",
        "@rubikon_news",
        "@russiatoday_de",
        "@reitschusterde",
        "@koppreport",
        "@SputnikDeutschland",
        "@SystemkritischeFilme",
        "@dokukiste",
        "@ddb_Radio",
        "@AntiSpiegel",
        "@BewusstTV",
        "@Nuoviso",
        "@Ken_FM",
        "@mmnews_offiziell",
        "@n23_tv",
        "@laser_lurch",
        "@de_2020news",
        "@KlagePATEN_eu",
        "QUERDENKEN",
        "@QUERDENKEN_711",
        "@aktivistmann",
        "@Polizeigewalt",
        "@terminkalender",
        "@demostream",
        "@KlagepatenElternInfo",
        "@Anwaelte_fuer_Aufklaerung",
        "@davidclaudiosiber",
        "@RA_Ludwig",
        "@militaernews",
        "@Demotermine",
        "@WiderstandAktiv",
        "@LivestreamsFuerDich",
        "@infotourstreams",
        "@militarbeobachter",
        "@Kinder_schuetzen",
        "@ReinerFuellmich",
        "@Mutigmacher_Kanal",
        "@Wiesollesweitergehen",
        "@etvideocontent",
        "@Frauen_Bustour",
        "@dday2_0_Kanal",
        "@Mahnwache_Berlin_Botschaften_US",
        "@MaskenpflichtSofort",
        "@busfahrerthomas",
        "@ffmspaziergang",
        "@RASattelmaier",
        "@aerztefueraufklaerung",
        "@WolfgangWodarg",
        "@Bodo_Schiffmann",
        "@coronainformationskanal",
        "@sucharitbhakdi_fanclub",
        "@robertfranznaturheilkunde",
        "@aerzte",
        "@zentrum_der_gesundheit",
        "@DieGermanische",
        "@Gesundheitsecke",
        "@naomiseibt",
        "@Corona_Fakten",
        "@denta_beaute",
        "@HolistischeGesundheitHeilung",
        "@QS24_tv",
        "@BodyEffects",
        "@weltdergesundheitTV",
        "@pandemimimi",
        "@KoronaAlarm",
        "@coronainformationskanal",
        "@kaibrenner",
        "@Corona_ist_nicht_das_Problem",
        "@Corona_Ausschuss",
        "@impfenmussfreiwilligbleiben",
        "@ZahnaerzteStehenAuf",
        "@Gesundheitsecke",
        "@AerzteKlaerenAuf",
        "@daswirdunsallebetreffen",
        "@ernstwolff",
        "@Cashkurs",
        "@TranslatedVideos",
        "@TranslatedPressDE",
        "@spioniker",
    ]

    print('downloading from telegram API')
    await get_groups_data(client, hints)

with client:
    client.loop.run_until_complete(main())